name: build-credential-helpers

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      pkgs:
        description: 'Packages to build (minimal, all or space separated list)'
        default: 'minimal'
        required: false
        type: string
      fail-fast:
        description: 'Fail fast'
        default: true
        required: false
        type: boolean
  push:
    branches:
      - 'main'
      - 'credential-helpers/[0-9]+.[0-9]+'
    paths:
      - '.github/workflows/.build.yml'
      - '.github/workflows/build-credential-helpers.yml'
      - 'common/**'
      - 'pkg/credential-helpers/**'
  pull_request:
    branches:
      - 'main'
      - 'credential-helpers/[0-9]+.[0-9]+'
    paths:
      - '.github/workflows/.build.yml'
      - '.github/workflows/build-credential-helpers.yml'
      - 'common/**'
      - 'pkg/credential-helpers/**'

jobs:
  run:
    uses: ./.github/workflows/.build.yml
    with:
      name: credential-helpers
    secrets: inherit
