name: build-compose

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      pkgs:
        description: 'Packages to build (minimal, all or space separated list)'
        default: 'minimal'
        required: false
        type: string
      fail-fast:
        description: 'Cancel all in-progress and queued jobs in the matrix if any job in the matrix fails'
        default: true
        required: false
        type: boolean
  push:
    branches:
      - 'main'
      - 'compose/[0-9]+.[0-9]+'
    paths:
      - '.github/workflows/.build.yml'
      - '.github/workflows/build-compose.yml'
      - 'common/**'
      - 'pkg/compose/**'
  pull_request:
    branches:
      - 'main'
      - 'compose/[0-9]+.[0-9]+'
    paths:
      - '.github/workflows/.build.yml'
      - '.github/workflows/build-compose.yml'
      - 'common/**'
      - 'pkg/compose/**'

jobs:
  run:
    uses: ./.github/workflows/.build.yml
    with:
      name: compose
    secrets: inherit
