name: manual-build

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      projects:
        description: 'Projects to build (all or space separated list)'
        default: 'all'
        required: false
        type: string
      pkgs:
        description: 'Packages to build (minimal, all or space separated list)'
        default: 'minimal'
        required: false
        type: string

jobs:
  prepare:
    runs-on: ubuntu-20.04
    outputs:
      matrix: ${{ steps.projects.outputs.matrix }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Create matrix
        id: projects
        run: |
          if [ "${{ inputs.projects }}" = "all" ]; then
            projects=$(find ./pkg -maxdepth 1 -type d -printf '%P ')
          else
            projects="${{ inputs.projects }}"
          fi
          projects=$(echo $projects | jq -cR 'split(" ")')
          echo "matrix=$projects" >>${GITHUB_OUTPUT}
      -
        name: Show matrix
        run: |
          echo ${{ steps.projects.outputs.matrix }}

  build:
    uses: ./.github/workflows/.release.yml
    needs:
      - prepare
    strategy:
      matrix:
        project: ${{ fromJson(needs.prepare.outputs.matrix) }}
    with:
      name: ${{ matrix.project }}
    secrets: inherit
